# logging的配置文件名
logging_config: 'logging.yaml'

# 数据集关键字
folder_keyword: ''
# 面料输入文件关键字
material_str: 'mianliao'
# 零件输入文件关键字
shape_str: 'lingjian'
# 昵称（输出文件时用到）
nick_name: 'jiangyincaijiao1'

# 缩放系数
scale: 10
# 额外间隔距离
extra_offset: 3
# 瑕疵的额外间隔距离
extra_hole_offset: 0
# 圆形瑕疵近似多边形边数
polygon_vertices: 100

# hausdorff距离阈值
hausdorff_threshold: 0

# 左底变种方法中，目标函数x轴初始权重
initial_weight: 0.5
# 左底变种方法中，目标函数x轴单次迭代增加权重
increment_weight: 0.1

# 邻域搜索次数
local_search_iteration: 0

# 是否为debug模式（是的话会输出单步迭代图片）
is_debug: False
# debug模式下读入的shape数量（仅仅在debug模式下有效）
debug_max_piece: 10

# PyClipper相关系数
clipper:
  meter_limit: 2
  arc_tolerance: 0.2
  precision: 1.2

production_data: '/tcdata'
production_output: 'DatasetC'
# 输入文件夹
input_folder: 'data'
# 输出文件夹
output_folder: 'submit'
# 图片输出文件夹
figure_folder: 'figure'

# 结果压缩包文件名
zip_file: 'submit.zip'
# nfps计算结果存储文件名后缀
nfps_json: 'nfps.json'
